[package]
name = "knn"
version = "0.1.0"
edition = "2024"

[lib]
name = "knn"
crate-type = ["rlib", "cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
numpy = "0.23"
ndarray = "0.16"
rayon = "1.10"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench_knn"
harness = false
