import numpy as np
from typing import List

class KnnClassifier:
    def __init__(self, k: int) -> None: ...
    def fit(self, x: np.ndarray, y: np.ndarray) -> None: ...
    def predict(self, x: np.ndarray) -> List[int]: ...
